### ISSUE TITLE
CSS Preprocessing

### ISSUE THREAD

**Issue by amhed** [gminaya/magic-boost#29]
We shouldn't have to repeat rule names.

Instead of
```css
.frontPage{
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-evenly;
  background-color: var(--dark-blue-navy);
}

.frontPage .logo{
  width: 400px;
}
```

```css
.frontPage{
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-evenly;
  background-color: var(--dark-blue-navy);

  .logo{
    width: 400px;
  }
}
```
